config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  #devise_for :users
  root to: 'posts#index'

  #establish restroutes resources
  resources :posts
  resources :profiles
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :body, length: { maximum: 240 }, allow_blank: false
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index]
    
    def index
        @post = Post.new
        #show posts on root/index page
        @posts = Post.all.order(created_at: :desc)
    end

    def create
        @post = current_user.posts.build(post_params)
        #below is for turbo. I had to add the format.html line in the .save line to get this to work
        #checking if turbo is bug after solving devise username addition
        respond_to do |format|
            if @post.save
                format.turbo_stream 
                format.html { redirect_to root_path } 
            else
                format.html do
                    flash[:post_errors] = @post.errors.full_messages
                    redirect_to root_path
                end
            end
        end
    end

    def edit

    end

    def update

    end

    def destroy
        @post = current_user.posts.find(params[:id])
        @post.destroy

        redirect_to root_path
        
    end

    private
        def post_params
            params.require(:post).permit(:body)
        end

       
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_controls.html.erb
<svg id="icon" style="max-height: 20px; padding-left: 10px;" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M14.046 2.242l-4.148-.01h-.002c-4.374 0-7.8 3.427-7.8 7.802 0 4.098 3.186 7.206 7.465 7.37v3.828c0 .108.044.286.12.403.142.225.384.347.632.347.138 0 .277-.038.402-.118.264-.168 6.473-4.14 8.088-5.506 1.902-1.61 3.04-3.97 3.043-6.312v-.017c-.006-4.367-3.43-7.787-7.8-7.788zm3.787 12.972c-1.134.96-4.862 3.405-6.772 4.643V16.67c0-.414-.335-.75-.75-.75h-.396c-3.66 0-6.318-2.476-6.318-5.886 0-3.534 2.768-6.302 6.3-6.302l4.147.01h.002c3.532 0 6.3 2.766 6.302 6.296-.003 1.91-.942 3.844-2.514 5.176z"></path></g></svg>   
<svg id="icon" style="max-height: 20px; padding-left: 10px;" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M23.77 15.67c-.292-.293-.767-.293-1.06 0l-2.22 2.22V7.65c0-2.068-1.683-3.75-3.75-3.75h-5.85c-.414 0-.75.336-.75.75s.336.75.75.75h5.85c1.24 0 2.25 1.01 2.25 2.25v10.24l-2.22-2.22c-.293-.293-.768-.293-1.06 0s-.294.768 0 1.06l3.5 3.5c.145.147.337.22.53.22s.383-.072.53-.22l3.5-3.5c.294-.292.294-.767 0-1.06zm-10.66 3.28H7.26c-1.24 0-2.25-1.01-2.25-2.25V6.46l2.22 2.22c.148.147.34.22.532.22s.384-.073.53-.22c.293-.293.293-.768 0-1.06l-3.5-3.5c-.293-.294-.768-.294-1.06 0l-3.5 3.5c-.294.292-.294.767 0 1.06s.767.293 1.06 0l2.22-2.22V16.7c0 2.068 1.683 3.75 3.75 3.75h5.85c.414 0 .75-.336.75-.75s-.337-.75-.75-.75z"></path></g></svg>        

<% if user_signed_in? && current_user == post.user %>

    <%= button_to post_path(post), method: :delete , form: { data: { turbo_confirm: "Are you sure?" } } do %>
      
        <svg id="icon" style="max-height: 20px; padding-left: 10px;" viewBox="0 0 24 24" aria-hidden="true">
            <g><path d="M20.746 5.236h-3.75V4.25c0-1.24-1.01-2.25-2.25-2.25h-5.5c-1.24 0-2.25 1.01-2.25 2.25v.986h-3.75c-.414 0-.75.336-.75.75s.336.75.75.75h.368l1.583 13.262c.216 1.193 1.31 2.027 2.658 2.027h8.282c1.35 0 2.442-.834 2.664-2.072l1.577-13.217h.368c.414 0 .75-.336.75-.75s-.335-.75-.75-.75zM8.496 4.25c0-.413.337-.75.75-.75h5.5c.413 0 .75.337.75.75v.986h-7V4.25zm8.822 15.48c-.1.55-.664.795-1.18.795H7.854c-.517 0-1.083-.246-1.175-.75L5.126 6.735h13.74L17.32 19.732z"></path>
            <path d="M10 17.75c.414 0 .75-.336.75-.75v-7c0-.414-.336-.75-.75-.75s-.75.336-.75.75v7c0 .414.336.75.75.75zm4 0c.414 0 .75-.336.75-.75v-7c0-.414-.336-.75-.75-.75s-.75.336-.75.75v7c0 .414.336.75.75.75z"></path>
            </g></svg>         
    <% end %>

    <% end %>

app/views/posts/_display.html.erb
<%= turbo_frame_tag "posts" do %>
    
    
    <%= render @posts %>
  
     
    <% end %>
 

app/views/posts/_form.html.erb
<%= form_with model: @post do |form|%>
    <% if form.object.errors.any? %>
        <h2><%= pluralize(form.object.errors.count, "error") %>
            forced this post from being saved</h2>
            <ul>
                <% form.object.errors.each do |error|%>
                <li><%= error.full_message %></li>
                <% end %>
            </ul>
    <% end %>
        
<div class="form-group pt-2 mb-2">
    <%= form.text_area :body, placeholder: "Pitter patter lets get at'er...", class:"form-control h-150"%>
    <div class="psh-submit">
        <%= form.submit "pshhh", class:"btn btn-primary btn-sm"%>
    </div>
</div>
        <% end %>

app/views/posts/_nav.html.erb
<div>
                
            <ul class="p-3 list-unstyled">
                <li>
                 <a class="link-light">
                    <%= link_to root_path do %>  
                    
                    <svg id="icon" style="max-height: 35px;" viewBox="0 0 24 24" aria-hidden="true" class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-lwhw9o r-dnmrzs r-bnwqim r-1plcrui r-lrvibr"><g><path d="M22.58 7.35L12.475 1.897c-.297-.16-.654-.16-.95 0L1.425 7.35c-.486.264-.667.87-.405 1.356.18.335.525.525.88.525.16 0 .324-.038.475-.12l.734-.396 1.59 11.25c.216 1.214 1.31 2.062 2.66 2.062h9.282c1.35 0 2.444-.848 2.662-2.088l1.588-11.225.737.398c.485.263 1.092.082 1.354-.404.263-.486.08-1.093-.404-1.355zM12 15.435c-1.795 0-3.25-1.455-3.25-3.25s1.455-3.25 3.25-3.25 3.25 1.455 3.25 3.25-1.455 3.25-3.25 3.25z"></path></g></svg>
                    <span class="badge">Home</span>
                    <% end %>
                    </a>
                    </li>
                <% if user_signed_in?%>
                <li class="pt-2">
                <a class="link-light">
                    <%= link_to profile_path(current_user) do %>  
                    
                    <svg id="icon" style="max-height: 35px;" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M12 11.816c1.355 0 2.872-.15 3.84-1.256.814-.93 1.078-2.368.806-4.392-.38-2.825-2.117-4.512-4.646-4.512S7.734 3.343 7.354 6.17c-.272 2.022-.008 3.46.806 4.39.968 1.107 2.485 1.256 3.84 1.256zM8.84 6.368c.162-1.2.787-3.212 3.16-3.212s2.998 2.013 3.16 3.212c.207 1.55.057 2.627-.45 3.205-.455.52-1.266.743-2.71.743s-2.255-.223-2.71-.743c-.507-.578-.657-1.656-.45-3.205zm11.44 12.868c-.877-3.526-4.282-5.99-8.28-5.99s-7.403 2.464-8.28 5.99c-.172.692-.028 1.4.395 1.94.408.52 1.04.82 1.733.82h12.304c.693 0 1.325-.3 1.733-.82.424-.54.567-1.247.394-1.94zm-1.576 1.016c-.126.16-.316.246-.552.246H5.848c-.235 0-.426-.085-.552-.246-.137-.174-.18-.412-.12-.654.71-2.855 3.517-4.85 6.824-4.85s6.114 1.994 6.824 4.85c.06.242.017.48-.12.654z"></path></g></svg>
                    <span class="badge">Profile</span>
                    <% end %>
                    </a>
                    <% end %>
                </li>
                </ul>
            </div> 

app/views/posts/_post.html.erb
<div id="<%= dom_id(post)%>">
    <div>
        <p class="text-muted fw-lighter">
            <%= profile_image(post.user) {style:"max-height: 5px; border-radius: 50%;"}%>
        @<%= link_to post.user.username, profile_path(post.user), data: { turbo: false }%></p>
        <p><%= post.body %></p>
        <div>
        <%= render "posts/controls", post: post %>    
        </div>
        
        <hr>
    </div>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts" do %>
    <%= render "post", post: @post %>
<% end %>

app/views/posts/destroy.turbo_stream.erb
<%= turbo_stream.remove @post %>

app/views/posts/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-2 pt-5" id="topcols">
        <%= link_to root_path, style:"text-decoration: none; font-size: 36px;" do %>
                    <span class="badge">pshChat</span>
                    <% end %>
        </div>
        <div class="col-md-7" id="topcols">
        <div>
                <%= render "form"%>
                </div>
        </div>
        <div class="col-sm-3" >
            
            <div class="pt-2"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2 pt-2" id="cols">
            <%= render "nav"%>
        </div>
        <div class="col-md-7 pt-2" id="cols">
            
            <div class="pt-2">
            <%= render "display"%>
            </div>
        </div>
        <div class="col-sm-3" id="othercols">
            <div>
                <div class="pt-3">
                <% if user_signed_in? %> 
                <div> Welcome <p class="fs-4"><%= current_user.username%> </p></div>
                <div class="text-muted"><%= current_user.email %> </div>  
                <%= button_to "Sign out", destroy_user_session_path, method: :delete, class:"btn btn-primary btn-sm" %> 
                <% else %>
                <%= button_to "Sign in", new_user_session_path, class:"btn btn-primary btn-sm" %> 
                <% end %>
            </div>
            </div>
        </div>
    </div>
</div>